var level1Sentences = [
  "Sending a message to a friend, buying a commodity, finding directions to your destination or simply keeping in touch with friends can all be challenging endeavors. However, the internet has changed the way we relate with our environment and our world in general.",
  "When people started capitalizing on the varied uses of internet, they understood the immense power it had. Regardless of what topic you want to know about, the internet is a knowledge hub with all kinds of details in it. You can research about absolutely any topic and even contribute.",
  "The advancements in technology have changed our lives in several ways, including how we communicate, how we do business, how we run our social and personal lives, etc. Thanks to the internet and the World Wide Web, the earth is now a global village.",
  "Apart from these, the continuous use of the internet can cause lifestyle disorders not only for the children but also for adults. Sitting in front of the computer for a prolonged time can affect your eyesight, cause obesity and related disorders. People tend to lose their productive time.",
  "Spamming is the dumping of bulk e-mails which are not solicited by the users. These e-mails can clog the whole system and serve no purpose. The spam e-mails can also contain potential threats like viruses, details of illegal activities, or soliciting money from the users.",
  "Although there are several advantages associated with the internet, we are also able to witness the horrendous disadvantages of the internet and its usage in all walks of life. It’s high time that we realize that technological advancements are like a double-edged sword .",
  "On the web, the traditional imperatives of reality vanish and there is a surprisingly wide variety of open potential outcomes. Such is the impact of the internet that a person sitting in one corner of the world can befriend another person from the other corner of the world without having met even once.",
  "The Internet has, by and large, proved to be useful for mankind. It has brought people and societies closer to each other. Moreover, it has made our lives so easy and fast. However, we must always remain aware of the ill effects of the internet and should follow the guidelines.",
  "The Banking sector has also been hugely benefitted from the internet. Earlier, you had long queues in banks which have now just vanished. Requesting a chequebook is now just a click away just like other banking services which are available on mobiles connected through the internet.",
  "The Internet, or what we have commonly known as the Net is something which has become a part of our lives. The Internet is basically a global system which is constituted of the Internet Protocol (IP) networks. But how it all started and from where did Internet originate is something quite interesting to know."
];

var level2Sentences =[
  "Flutter is a free and open-source mobile UI framework created by Google and released in May 2017. In a few words, it allows you to create a native mobile application with only one codebase. This means that you can use one programming language and one codebase to create two different apps. To develop with Flutter, you will use a programming language called Dart. The language was created by Google in October 2011, but it has improved a lot over these past years. Dart focuses on front-end development, and you can use it to create mobile and web applications. If you know a bit of programming, Dart is a typed object programming language.",
  "Flutter is a modern framework, and you can feel it! It’s way simpler to create mobile applications with it. If you have used Java, Swift, or React Native, you'll notice how Flutter is different. I personally never liked mobile application development before I started using Flutter. What I love about Flutter is that you can create a real native application without a bunch of code. Thanks to Flutter, you can change your code and see the results in real-time. It’s called Hot-Reload. It only takes a short amount of time after you save to update the application itself. Significant modifications force you to reload the app.",
  "The docs say A widget is an immutable description of part of a user interface. A human being will tell you it's a Blueprint, which is a much easier way to think about it. However, one also needs to keep in mind there are many types of Widgets in Flutter, and you cannot see or touch all of them. Text is a Widget, but so is its TextStyle, which defines things like size, color, font family and weight. There are Widgets that represent things, ones that represent characteristics and even others that do things, like FutureBuilder and StreamBuilder. Complex widgets can be created by combining many simpler ones.",
  "Mobile app development is a relatively recent field of endeavor. Third-party developers have been able to build mobile apps for less than a decade, so it is no surprise that tools are still evolving. Your app talks to the platform to create widgets, or access services like the camera. The widgets are rendered to a screen canvas, and events are passed back to the widgets. This is a simple architecture, but you pretty much have to create separate apps for each platform because the widgets are different, not to mention the native languages. Recall that in Flutter, the widgets and the renderer have been lifted up out of the platform into the user’s app.",
  "The first cross-platform frameworks were based on JavaScript and WebViews. Examples include a family of related frameworks: PhoneGap, Apache Cordova, Ionic, and others. Before Apple released their iOS SDK they encouraged third party developers to build webapps for the iPhone, so building cross-platform apps using web technologies was an obvious step. Your app creates HTML and displays it in a WebView on the platform. Note that it is difficult for languages like JavaScript to talk directly to native code (like the services) so they go through a “bridge” that does context switches between the JavaScript realm and the native realm.",
  "CSS includes a number of layout models, including (multiple) box models, floating elements, tables, multiple columns of text, paged media, and so on. Additional layout models, like flexbox and grid, were added later because developers and designers needed more control over layout and were using tables and transparent images to get what they wanted. In traditional layout new layout models cannot be added by the developer, so flexbox and grid had to be added to CSS and implemented on all browsers. Another problem with traditional layout is that the rules can interact (and even conflict) with each other.",
  "Flutter includes quite a few widgets for doing layout, not just columns but also rows, grids, lists, etc. In addition, Flutter has a unique layout model we call the “sliver layout model” which is used for scrolling. Layout in Flutter is so fast it can be used for scrolling. Think about that for a moment. Scrolling must be so instantaneous and smooth that the user feels like the screen image is attached to their finger as they drag it across the physical screen. By using layout for scrolling, Flutter can implement advanced kinds of scrolling, like these shown below. Note that these are animated GIF images, Flutter is even smoother.",
  "Because widgets are now part of the app, new widgets can be added and existing widgets can be customized to give them a different look or feel, or to match a company’s brand. The trend in mobile design is away from the cookie cutter apps that were common a few years ago and toward custom designs that delight users and win awards. Flutter comes with rich, customizable widget sets for Android, iOS, and Material Design (in fact, we have been told that Flutter has one of the highest fidelity implementations of Material Design). We used the customizability of Flutter to build these widget sets, to match the look and feel of native widgets on multiple platforms.",
  "Libraries for reactive web views introduced virtual DOM. DOM is the HTML Document Object Model, an API used by JavaScript to manipulate an HTML document, represented as a tree of elements. Virtual DOM is an abstract version of the DOM created using objects in the programming language, in this case JavaScript. In reactive web views (implemented by systems like ReactJS and others) the virtual DOM is immutable, and is rebuilt from scratch each time anything changes. The virtual DOM is compared to the real DOM to generate a set of minimal changes, which are then executed to update the real DOM. Finally, the platform re-renders the real DOM and paints it into a canvas.",
  "React Native does a similar thing, but for mobile apps. Instead of DOM, it manipulates the native widgets on the mobile platform. Instead of a virtual DOM, It builds a virtual tree of widgets and compares it to the native widgets and only updates those that have changed. Remember that React Native has to communicate with the native widgets through the bridge, so the virtual tree of widgets helps keep passes over the bridge to a minimum, while still allowing the use of native widgets. Finally, once the native widgets are updated, the platform then renders them to the canvas. React Native is a big win for mobile development, and was an inspiration for Flutter."
  
];

var level3Sentences=[
  "Python is an interpreted, object-oriented, high-level programming language with dynamic semantics. Its high-level built in data structures, combined with dynamic typing and dynamic binding, make it very attractive for Rapid Application Development, as well as for use as a scripting or glue language to connect existing components together. Python's simple, easy to learn syntax emphasizes readability and therefore reduces the cost of program maintenance. Python supports modules and packages, which encourages program modularity and code reuse. The Python interpreter and the extensive standard library are available in source or binary form without charge for all major platforms, and can be freely distributed. Often, programmers fall in love with Python because of the increased productivity it provides. Since there is no compilation step, the edit-test-debug cycle is incredibly fast. Debugging Python programs is easy: a bug or bad input will never cause a segmentation fault.",
  "In Java, everything is an Object. Java can be easily extended since it is based on the Object model. Unlike many other programming languages including C and C++, when Java is compiled, it is not compiled into platform specific machine, rather into platform independent byte code. This byte code is distributed over the web and interpreted by the Virtual Machine (JVM) on whichever platform it is being run on. Java is designed to be easy to learn. If you understand the basic concept of OOP Java, it would be easy to master. With Java's secure feature it enables to develop virus-free, tamper-free systems. Authentication techniques are based on public-key encryption.  Java compiler generates an architecture-neutral object file format, which makes the compiled code executable on many processors, with the presence of Java runtime system. Java makes an effort to eliminate error prone situations by emphasizing mainly on compile time error checking and runtime checking.",
  "C is a procedural programming language. It was initially developed by Dennis Ritchie in the year 1972. It was mainly developed as a system programming language to write an operating system. The main features of C language include low-level access to memory, a simple set of keywords, and clean style, these features make C language suitable for system programmings like an operating system or compiler development. Many later languages have borrowed syntax/features directly or indirectly from C language. Like syntax of Java, PHP, JavaScript, and many other languages are mainly based on C language. C++ is nearly a superset of C language (There are few programs that may compile in C, but not in C++). After the above discussion, we can formally assess the structure of a C program. By structure, it is meant that any program can be written in this structure only. Writing a C program in any other structure will hence lead to a Compilation Error.",
  "C++ is a programming language developed by Bjarne Stroustrup in 1979 at Bell Labs. C++ is regarded as a middle-level language, as it comprises a combination of both high-level and low-level language features. It is a superset of C, and that virtually any legal C program is a legal C++ program. C++ runs on a variety of platforms, such as Windows, Mac OS, and the various versions of UNIX. A programming language is claimed to use static typing when type checking is performed during compile-time as opposed to run-time. A compiled language is a programming language whose implementations are typically compilers (translators that generate machine code from source code), and not interpreters (step-by-step executors of source code, where no pre-runtime translation takes place). A general-purpose language could be a language that is generally applicable across application domains, and lacks specialized options for a specific domain. This is in contrast to a domain specific language.",
  "React is a popular and widely used programming language at present since almost every web developer or a full-stack developer is using it. Sounds interesting right? Let’s read all about React here. SPA is an application which loads single HTML page instead of reloading entire page from the server during interacts with the app. It updates pages dynamically while interacts with the app. React was created by jorden walk, and it is maintained by Facebook and the community of individual developer. React is the most powerful frontend library to develop View part from MVC. All web developer already know javascript so. it is quite easy to learn. Those who not from web development background or new to web development need to learn javascript first. especially the latest javascript ES6. React application is fast. It Renders and Re-renders Applications quickly and keeps updated with the latest change in data. React-based Application is faster which gives the great user experience by the end of the day your application performance is a matter which makes your user happy.",
  "C# is a general-purpose, modern and object-oriented programming language pronounced as C sharp. C# is among the languages for Common Language Infrastructure. C# has many other reasons for being popular and in demand. C# is a high-level language so it is closer to other popular programming languages like C, C++, and Java and thus becomes easy to learn for anyone. C# is widely used for developing web applications and Desktop applications. It is one of the most popular languages that is used in professional desktop. If anyone wants to create Microsoft apps, C# is their first choice. The larger the community the better it is as new tools and software will be developing to make it better. C# has a large community so the developments are done to make it exist in the system and not become extinct. C# is widely used in game development and will continue to dominate. C# integrates with Microsoft and thus has a large target audience. The C# features such as Automatic Garbage Collection, interfaces, object-oriented, etc. make C# a popular game developing language."
];
